export const IS_FETCHING_ACTION = 'IS_FETCHING_ACTION'
export const SET_USER_LIST_ACTION = 'SET_USER_LIST_ACTION'
export const SET_TOTAL_USERS_QUANTITY_ACTION = 'SET_TOTAL_USERS_QUANTITY_ACTION'
export const FOLLOW_ACTION = 'FOLLOW'
export const UNFOLLOW_ACTION = 'UNFOLLOW'
export const SET_CURRENT_PAGE_NUMBER_ACTION = 'SET_CURRENT_PAGE_NUMBER_ACTION'

export const SET_USER_PROFILE_ACTION = 'SET_USER_PROFILE_ACTION'
export const SET_USER_STATUS_ACTION = 'SET_USER_STATUS_ACTION'

export const LOGIN_ACTION = 'LOGIN_ACTION'
export const SET_MY_USER_DATA_ACTION = 'SET_MY_USER_DATA_ACTION'
export const SET_USER_PHOTO_ACTION = 'SET_USER_PHOTO_ACTION'

export const LOAD_BLOG_LIST_ACTION = 'LOAD_BLOG_LIST_ACTION'
